### ISSUE TITLE
Wow thank you!

### ISSUE THREAD

**Issue by dabateman** [Gordon999/Pi-Camera-GUI#1]
Thank you so much for this script. 
I have been extremely slowly trying to write something like this over the last year.
With yours it was easy to add the -r tag for attached raw and change the saved directory. 

Now I may play with it to use ISO only for auto then if not auto switch to using just analog gain (-ag) from 1 to 16. 
I also may have space on my 800x480 screen to add another row for PiDNG conversion of the folder with saved raw jpegs to DNG files and tiffs.

Alternatively I might just switch out the core (raspistill) and use libcamera-still,  which automatically makes DNG files with the jpegs.  Its just having problems this month. But uses the same features. 

For mine I have been hung up on adding sliders on the top for zoom, left side for y displacement and bottom for x displacement.  I wanted this to zoom in for finer focusing of the preview window.  But I never figured it out, and never got anywhere as started with that. If you could figure that out it would make this perfect. 

No issues yet. Just wanted to say thank you for a clean, clear script with descriptions.

**Comment by Gordon999** [comment]
Thanks.

I have done some work on it. See Pi_Camera_GUI2.py .

You can select to save jpg/bmp/gif/png format stills.

You can zoom in. Click on the picture where to zoom, shown by a red cross, then click on the Zoom button.
It will show a FOC figure, focus for maximum value. Click on Zoomed to exit Zoom.

**Comment by Gordon999** [comment]
You will need opencv..

sudo apt-get install python3-opencv

**Comment by dabateman** [comment]
Thank you this looks good. The zoom works.

**Comment by Gordon999** [comment]
closed
