### ISSUE TITLE
Zoom location can't move, no box

### ISSUE THREAD

**Issue by dabateman** [Gordon999/Pi-Camera-GUI#2]
Hello,
Version 6 is interesting with the zoom in control.  I can zoom in about 4 times. I think its the 5 and 6 setting just kicks back to full window. 
However,  there isn't a box anymore to move the central cross. So zooming only seems to be fixed at the central point.
Can the box be added back or is that the cost of having zoom control. 

Also I noticed the last version added a yellow line across the lower part of the frame.  Is there a purpose for that?

**Comment by Gordon999** [comment]
Thanks for the feedback. I added the levels of Zoom but then it got complicated to add the boxes for all the levels and sizes.
As a compromise I have added a FOCUS button which will work how the original zoom worked and zoom to the box shown, in addition it will also record images and videos at that size.
You can only operate the FOCUS button if the ZOOM button is off, and visa versa.
The yellow line was a first attempt at showing the video format eg 16x9 format, it worked for 1280x720 but not 1920x1080, but clearly I hadn't finished it . Now improved to show video cropping
Let me know how it goes.

**Comment by dabateman** [comment]
Yes this works. The focus will center in where selected.  It also looks to record a 640x480 image, if still set at that point and zoomed. So you have a movable fixed zoom image.

The zoom feature is interesting,  to get a 640x480 crop right away.

So all working now.
One modification I may try is to change the ISO behavior.  To have ISO auto, and if not auto than only adjust analog gain from 1 to 16 with digital gain fixed at 1.

**Comment by Gordon999** [comment]
I've uploaded v9. modified saved zoomed images sizes and improved zoomed video quality, added --mode 2,  please check it works OK

**Comment by Gordon999** [comment]
I assume this is now fixed.

**Comment by dabateman** [comment]
Yes I got version 9 working.  It was crashing at first loose Mmal, but I think I was too fast in selecting things. If you wait for it it works.
I see now the maximum image saved resolution is only 3200x2400. The zooms save from steps down from that to 640x480.

**Comment by Gordon999** [comment]
Hopefully fixed in v11. I've never seen the mmal error.

**Comment by dabateman** [comment]
Yes looks to be fixed now.
It is full resolution without zoom, then zoom setting only to 4 which goes to 640x480.
The focus also works. 

On my version I was able to remove the image file save format and switched it to image effects.  Your new version with limits at the top made that easy. 

The harder part will see if I can make this for libcamera-still, as base software instead of raspistill.  That seems to be what the pi will switch to in the near future.  A bunch of the settings are different.

**Comment by Gordon999** [comment]
v12. I have added effects, awb and metering options.

I plan to goto libcamera when bullseye is on the Pi.

**Comment by dabateman** [comment]
Version 12 is excellent.  The greyworld AWB setting is better than setting 1:1 for red and blue with my monochrome converted HQ camera. 
So far everything is working. 

I look forward to the libcamera-still version.

**Comment by Gordon999** [comment]
closed, now on version 16

**Comment by dabateman** [comment]
Funny today Bullseye was released. 
I will still have to test the new version 16 with DRC selection.

**Comment by Gordon999** [comment]
Working on it  but bit of a nightmare at the moment with libcamera , pygame and SDL changes

**Comment by dabateman** [comment]
Yes the mode has changed, ISO is gone.  Many changes actually for Libcamera-still. 

I tried version 16 (download an hour ago) and I get an error that tinterval is not specified. Odd as Version 12 worked and I don't see any issues there looking at the code quickly.

**Comment by Gordon999** [comment]
Hopefully fixed in v17.

Libcamera version  progressing. Hopefully a beta version tomorrow.

**Comment by Gordon999** [comment]
Beta at https://github.com/Gordon999/Pi_LIbCamera_GUI.

Still trying to get to terms with some changes relative to raspistill etc

**Comment by dabateman** [comment]
Wow you are lightning quick. 
I tested v17 and it works. I see v16 was just missing a line in the config file.
I will have to get Bullseye installed and test this out. I now have an extra micro sd card to try.

**Comment by dabateman** [comment]
Pi_LibCamera is interesting.  I don't know why but adjusting the brightness seem to crash it. Maybe as its divided by 100 for the range. But it doesn't always crash. 
Changing the gain limit to 20 works better. The HQ analog gain goes up to 16, then digital gain is added above that.
The HQ can handle video frames up to 50, so I made that change and 2028x1080 at 50fps worked when I added it. I did get some frame drops down to 24. So its not stable. 
Adding up to 120 fps didn't work. So 90 fps might be the limit.
In the two empty blocks you could add -- denoise and -- sharpness.  Those are the only other options I can see available in libcamera-still. 
Ev for some reason didn't work for me. Changing it didn't do anything.  I didn't inspect its tag though. 

I was trying to add the raw tag, but didn't work. Using 'jpg -r' would save a jpeg and DNG file but then it locks up and doesn't leave the saving file screen. The correct tag might just be --raw. With out jpg, but that would need to be added as on alternative, as the file type doesn't recognize it.

**Comment by Gordon999** [comment]
Comment moved to https://github.com/Gordon999/Pi_LIbCamera_GUI issues
